CREATE TABLE IF NOT EXISTS PRODUCT_FEATURE_CATEGORIES (
  feature TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
