CREATE TABLE IF NOT EXISTS PRODUCT_FEATURES (
  id TEXT PRIMARY KEY,
  product_id TEXT NOT NULL,
  feature_category_id TEXT,
  name TEXT NOT NULL,
  clsv TEXT,
  journey TEXT,
  status TEXT,
  progress INTEGER NOT NULL DEFAULT 0,
  orbit INTEGER,
  angle INTEGER,
  size INTEGER,
  effort TEXT,
  rank TEXT,
  impact TEXT,
  eta TEXT,
  outcomes TEXT,
  votes INTEGER NOT NULL DEFAULT 0,
  description TEXT NOT NULL,
  applicable_segments TEXT,
  applicable_institution_types TEXT,
  loan_types TEXT,
  triggers TEXT,
  maturity_level TEXT,
  keywords TEXT,
  exclusion_signals TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(product_id, name),
  FOREIGN KEY (product_id) REFERENCES PRODUCTS(id),
  FOREIGN KEY (feature_category_id) REFERENCES PRODUCT_FEATURE_CATEGORIES(id)
);
