PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS PRODUCT_FEATURE_CATEGORIES_NEW (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO PRODUCT_FEATURE_CATEGORIES_NEW (id, category)
SELECT 'PFCT-001', 'Syndication / Complex Lending'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_FEATURE_CATEGORIES_NEW WHERE id = 'PFCT-001');

INSERT INTO PRODUCT_FEATURE_CATEGORIES_NEW (id, category)
SELECT 'PFCT-002', 'Monitoring & Controls'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_FEATURE_CATEGORIES_NEW WHERE id = 'PFCT-002');

INSERT INTO PRODUCT_FEATURE_CATEGORIES_NEW (id, category)
SELECT 'PFCT-003', 'Credit & Risk'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_FEATURE_CATEGORIES_NEW WHERE id = 'PFCT-003');

INSERT INTO PRODUCT_FEATURE_CATEGORIES_NEW (id, category)
SELECT 'PFCT-004', 'Platform Services'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_FEATURE_CATEGORIES_NEW WHERE id = 'PFCT-004');

INSERT INTO PRODUCT_FEATURE_CATEGORIES_NEW (id, category)
SELECT 'PFCT-005', 'SBA & Re-Amort, Servicing'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_FEATURE_CATEGORIES_NEW WHERE id = 'PFCT-005');

INSERT INTO PRODUCT_FEATURE_CATEGORIES_NEW (id, category)
SELECT 'PFCT-006', 'Analytics & Inquiry'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_FEATURE_CATEGORIES_NEW WHERE id = 'PFCT-006');

INSERT INTO PRODUCT_FEATURE_CATEGORIES_NEW (id, category)
SELECT 'PFCT-007', 'Servicing'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_FEATURE_CATEGORIES_NEW WHERE id = 'PFCT-007');

INSERT INTO PRODUCT_FEATURE_CATEGORIES_NEW (id, category)
SELECT 'PFCT-008', 'Origination'
WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_FEATURE_CATEGORIES_NEW WHERE id = 'PFCT-008');

UPDATE PRODUCT_FEATURES
SET feature_category_id = CASE feature_category_id
  WHEN 'PFC-001' THEN 'PFCT-001'
  WHEN 'PFC-019' THEN 'PFCT-001'

  WHEN 'PFC-002' THEN 'PFCT-002'
  WHEN 'PFC-006' THEN 'PFCT-002'
  WHEN 'PFC-011' THEN 'PFCT-002'
  WHEN 'PFC-014' THEN 'PFCT-002'

  WHEN 'PFC-003' THEN 'PFCT-003'
  WHEN 'PFC-004' THEN 'PFCT-003'
  WHEN 'PFC-005' THEN 'PFCT-003'
  WHEN 'PFC-021' THEN 'PFCT-003'

  WHEN 'PFC-007' THEN 'PFCT-004'
  WHEN 'PFC-012' THEN 'PFCT-004'
  WHEN 'PFC-020' THEN 'PFCT-004'

  WHEN 'PFC-008' THEN 'PFCT-005'

  WHEN 'PFC-009' THEN 'PFCT-006'
  WHEN 'PFC-013' THEN 'PFCT-006'
  WHEN 'PFC-016' THEN 'PFCT-006'

  WHEN 'PFC-010' THEN 'PFCT-007'
  WHEN 'PFC-015' THEN 'PFCT-007'

  WHEN 'PFC-017' THEN 'PFCT-008'
  WHEN 'PFC-018' THEN 'PFCT-008'

  ELSE feature_category_id
END
WHERE feature_category_id LIKE 'PFC-%';

DROP TABLE IF EXISTS PRODUCT_FEATURE_CATEGORIES;
ALTER TABLE PRODUCT_FEATURE_CATEGORIES_NEW RENAME TO PRODUCT_FEATURE_CATEGORIES;

PRAGMA foreign_keys = ON;
