type SeedRow = Record<string, string | number>;

export interface SeedTableDefinition {
  id: string;
  label: string;
  rows: SeedRow[];
}

const productsRows: SeedRow[] = [
  { id: "PRD-001", category: "Lending", subcategory: "Origination Solutions", name: "Credit Assessment" },
  { id: "PRD-002", category: "Lending", subcategory: "Origination Solutions", name: "Consumer & SMB Loan Origination" },
  { id: "PRD-003", category: "Lending", subcategory: "Origination Solutions", name: "Commercial Loan Origination" },
  { id: "PRD-004", category: "Lending", subcategory: "Servicing Solutions", name: "Consumer & SMB Loan Servicing" },
  { id: "PRD-005", category: "Lending", subcategory: "Servicing Solutions", name: "Commercial Loan Servicing" },
  { id: "PRD-006", category: "Lending", subcategory: "Specialty Lending Solutions", name: "Asset & Auto Finance" },
  { id: "PRD-007", category: "Lending", subcategory: "Specialty Lending Solutions", name: "Supply Chain Finance" },
  { id: "PRD-008", category: "Lending", subcategory: "Specialty Lending Solutions", name: "Syndication and Distribution" },
];

const institutionProfileRows: SeedRow[] = [
  {
    id: "IP-001",
    institution_name: "Crédit Agricole CIB (CA-CIB)",
    institution_type: "Global Investment Bank",
    business_lines: "Corporate Banking, Project Finance, Structured Finance, Capital Markets",
    target_segments: "Large Corporate, Infrastructure Sponsors, Energy",
    geography: "Global (EU, Americas, APAC)",
    known_strengths: "Project finance leadership, structured lending, energy transition financing",
    signals: "participates in syndicated loans, complex cross-border deals, multi-currency facilities",
  },
  {
    id: "IP-002",
    institution_name: "Farmer Mac",
    institution_type: "Government-Sponsored Enterprise",
    business_lines: "Agricultural Finance, Secondary Loan Market, Structured Agricultural Lending",
    target_segments: "Agricultural Lenders, Rural Utilities, Farm Operators",
    geography: "United States (Rural Markets)",
    known_strengths: "Secondary agricultural loan market, risk transfer for farm credit institutions",
    signals: "securitizes agricultural loans, regulatory compliance focus, portfolio-level loan monitoring",
  },
  {
    id: "IP-003",
    institution_name: "JPMorgan Chase",
    institution_type: "Global Universal Bank",
    business_lines: "Corporate Banking, Investment Banking, Treasury Services, Commercial Lending",
    target_segments: "Global Corporates, Middle Market, Institutional Clients",
    geography: "Global",
    known_strengths: "Syndicated lending leader, treasury services scale, complex credit structuring",
    signals: "participates in large syndicated loans, complex facility structures, multi-jurisdiction lending",
  },
  {
    id: "IP-004",
    institution_name: "Capital One",
    institution_type: "Large U.S. Bank",
    business_lines: "Commercial Banking, Credit Cards, Consumer Lending, Digital Banking",
    target_segments: "Middle Market, Commercial Real Estate, Consumers",
    geography: "United States",
    known_strengths: "Data-driven credit models, digital banking capabilities",
    signals: "strong credit risk analytics, commercial real estate lending, high-volume loan servicing",
  },
  {
    id: "IP-005",
    institution_name: "Citizens Bank",
    institution_type: "Regional Bank",
    business_lines: "Commercial Banking, Corporate Finance, Asset-Based Lending",
    target_segments: "Middle Market Companies, Regional Businesses",
    geography: "United States (Northeast, Midwest)",
    known_strengths: "Middle-market lending, asset-based lending expertise",
    signals: "participates in syndicated deals, collateralized lending structures",
  },
  {
    id: "IP-006",
    institution_name: "First Horizon Bank",
    institution_type: "Regional Bank",
    business_lines: "Commercial Banking, Wealth Management, Treasury Services",
    target_segments: "Small Business, Middle Market",
    geography: "United States (Southeast)",
    known_strengths: "Relationship banking, regional commercial lending",
    signals: "moderate facility complexity, secured commercial loans",
  },
  {
    id: "IP-007",
    institution_name: "BNP Paribas",
    institution_type: "Global Universal Bank",
    business_lines: "Corporate Banking, Capital Markets, Trade Finance, Structured Finance",
    target_segments: "Global Corporations, Institutional Investors",
    geography: "Global (Europe-focused)",
    known_strengths: "Structured finance, cross-border financing, derivatives integration",
    signals: "multi-currency lending, syndicated credit facilities, regulatory-heavy environments",
  },
  {
    id: "IP-008",
    institution_name: "Third Coast Bank",
    institution_type: "Community / Regional Bank",
    business_lines: "Commercial Banking, CRE Lending, Treasury Management",
    target_segments: "Local Businesses, Small-to-Mid Commercial Clients",
    geography: "United States (Texas)",
    known_strengths: "Commercial real estate lending, relationship banking",
    signals: "secured commercial lending, moderate loan servicing needs",
  },
  {
    id: "IP-009",
    institution_name: "CIT Group",
    institution_type: "Commercial Bank / Specialty Finance",
    business_lines: "Equipment Finance, Commercial Lending, Factoring",
    target_segments: "Middle Market, Transportation, Manufacturing",
    geography: "United States",
    known_strengths: "Equipment finance leadership, asset-backed lending",
    signals: "heavy collateral management, asset-based loan monitoring",
  },
  {
    id: "IP-010",
    institution_name: "First Republic Bank",
    institution_type: "Private / Relationship Bank",
    business_lines: "Private Banking, Commercial Lending, Wealth Management",
    target_segments: "High-Net-Worth Individuals, Professional Services Firms",
    geography: "United States (Coastal markets)",
    known_strengths: "Relationship lending, jumbo mortgage lending",
    signals: "relatively simple facility structures, relationship-based underwriting",
  },
];

const productFeatureCategoryRows: SeedRow[] = [
  { id: "PFCT-001", category: "Syndication / Complex Lending" },
  { id: "PFCT-002", category: "Monitoring & Controls" },
  { id: "PFCT-003", category: "Credit & Risk" },
  { id: "PFCT-004", category: "Platform Services" },
  { id: "PFCT-005", category: "SBA & Re-Amort, Servicing" },
  { id: "PFCT-006", category: "Analytics & Inquiry" },
  { id: "PFCT-007", category: "Servicing" },
  { id: "PFCT-008", category: "Origination" },
  { id: "PFCT-009", category: "Digital Experience" },
  { id: "PFCT-010", category: "Customer Risk & Credit" },
];

const productFeaturesRows: SeedRow[] = [
  { id: "PF-001", product_id: "PRD-005", feature_category_id: "PFCT-006", name: "Facility History", clsv: "CLSV-706", journey: "inquiry", status: "design-complete", progress: 90, votes: 112, eta: "Q2 2026" },
  { id: "PF-002", product_id: "PRD-005", feature_category_id: "PFCT-007", name: "Payoff Event", clsv: "CLSV-751+714", journey: "payoff", status: "design-complete", progress: 88, votes: 98, eta: "Q2 2026" },
  { id: "PF-003", product_id: "PRD-005", feature_category_id: "PFCT-002", name: "Loan: Collateral", clsv: "CLSV-724", journey: "collateral", status: "design-complete", progress: 95, votes: 76, eta: "Q1 2026" },
  { id: "PF-004", product_id: "PRD-005", feature_category_id: "PFCT-002", name: "Facility: Collateral", clsv: "CLSV-693", journey: "collateral", status: "design-complete", progress: 85, votes: 61, eta: "Q2 2026" },
  { id: "PF-005", product_id: "PRD-005", feature_category_id: "PFCT-007", name: "Facility Invoices", clsv: "CLSV-707", journey: "booking", status: "design-complete", progress: 80, votes: 54, eta: "Q2 2026" },
  { id: "PF-006", product_id: "PRD-005", feature_category_id: "PFCT-008", name: "Reference Repayment Schedules", clsv: "CLSV-673", journey: "booking", status: "design-complete", progress: 78, votes: 91, eta: "Q2 2026" },
  { id: "PF-007", product_id: "PRD-005", feature_category_id: "PFCT-004", name: "EIR Fees", clsv: "CLSV-876", journey: "booking", status: "planned", progress: 0, votes: 74, eta: "Q3 2026" },
  { id: "PF-008", product_id: "PRD-005", feature_category_id: "PFCT-002", name: "ECC Collateral Controls", clsv: "CLSV-698", journey: "collateral", status: "planned", progress: 0, votes: 88, eta: "Q3 2026" },
  { id: "PF-009", product_id: "PRD-005", feature_category_id: "PFCT-006", name: "Loan History Views", clsv: "CLSV-863", journey: "inquiry", status: "planned", progress: 0, votes: 53, eta: "Q3 2026" },
  { id: "PF-010", product_id: "PRD-005", feature_category_id: "PFCT-003", name: "Trouble Asset Manager", clsv: "CLSV-738", journey: "maintenance", status: "planned", progress: 0, votes: 67, eta: "Q3 2026" },
  { id: "PF-011", product_id: "PRD-005", feature_category_id: "PFCT-001", name: "Assignment Manager", clsv: "CLSV-754", journey: "booking", status: "planned", progress: 0, votes: 59, eta: "Q4 2026" },
  { id: "PF-012", product_id: "PRD-005", feature_category_id: "PFCT-004", name: "FX Rate Controls", clsv: "CLSV-752", journey: "booking", status: "planned", progress: 0, votes: 41, eta: "Q4 2026" },
  { id: "PF-013", product_id: "PRD-005", feature_category_id: "PFCT-003", name: "Cross-Limit Controls", clsv: "CLSV-689", journey: "booking", status: "future", progress: 0, votes: 45, eta: "Q1 2027" },
  { id: "PF-014", product_id: "PRD-005", feature_category_id: "PFCT-002", name: "Collateral Doc Tracker", clsv: "CLSV-732", journey: "collateral", status: "future", progress: 0, votes: 38, eta: "Q1 2027" },
  { id: "PF-015", product_id: "PRD-005", feature_category_id: "PFCT-003", name: "Customer Flowdown & Pooling", clsv: "CLSV-680", journey: "booking", status: "future", progress: 0, votes: 31, eta: "Q2 2027" },
  { id: "PF-016", product_id: "PRD-005", feature_category_id: "PFCT-006", name: "Pro Rata & SNC Reporting", clsv: "CLSV-712", journey: "inquiry", status: "future", progress: 0, votes: 28, eta: "Q2 2027" },
  { id: "PF-017", product_id: "PRD-005", feature_category_id: "PFCT-005", name: "Escrow, SBA & Re-Amort", clsv: "CLSV-726", journey: "scheduled", status: "future", progress: 0, votes: 36, eta: "Q2 2027" },
  { id: "PF-018", product_id: "PRD-005", feature_category_id: "PFCT-004", name: "System Admin Suite", clsv: "CLSV-E-116", journey: "sysadmin", status: "future", progress: 0, votes: 55, eta: "TBD" },
  { id: "PF-019", product_id: "PRD-005", feature_category_id: "PFCT-003", name: "Customer Risk & Credit", clsv: "CLSV-676", journey: "booking", status: "future", progress: 0, votes: 33, eta: "Q3 2027" },
  { id: "PF-020", product_id: "PRD-005", feature_category_id: "PFCT-008", name: "Renewal / Mod / Amendments", clsv: "CLSV-E-114", journey: "renewal", status: "future", progress: 0, votes: 62, eta: "Q3 2027" },
  { id: "PF-021", product_id: "PRD-005", feature_category_id: "PFCT-001", name: "Syndication", clsv: "CLSV-E-119", journey: "syndication", status: "future", progress: 0, votes: 48, eta: "TBD" },
  { id: "PF-022", product_id: "PRD-005", feature_category_id: "PFCT-009", name: "Borrower Intake", clsv: "SEED-022", journey: "digital-experience", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-023", product_id: "PRD-005", feature_category_id: "PFCT-009", name: "Self-Service", clsv: "SEED-023", journey: "digital-experience", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-024", product_id: "PRD-005", feature_category_id: "PFCT-009", name: "Document/Funding Transition", clsv: "SEED-024", journey: "digital-experience", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-025", product_id: "PRD-005", feature_category_id: "PFCT-008", name: "Application Workflow", clsv: "SEED-025", journey: "origination", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-026", product_id: "PRD-005", feature_category_id: "PFCT-008", name: "Underwriting", clsv: "SEED-026", journey: "origination", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-027", product_id: "PRD-005", feature_category_id: "PFCT-008", name: "Pricing / Approval", clsv: "SEED-027", journey: "origination", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-028", product_id: "PRD-005", feature_category_id: "PFCT-008", name: "Onboarding to Servicing", clsv: "SEED-028", journey: "origination", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-029", product_id: "PRD-005", feature_category_id: "PFCT-010", name: "Credit Assessment", clsv: "SEED-029", journey: "customer-risk-credit", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-030", product_id: "PRD-005", feature_category_id: "PFCT-010", name: "Risk Rating", clsv: "SEED-030", journey: "customer-risk-credit", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-031", product_id: "PRD-005", feature_category_id: "PFCT-010", name: "Exposure Visibility", clsv: "SEED-031", journey: "customer-risk-credit", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-032", product_id: "PRD-005", feature_category_id: "PFCT-010", name: "Compliance Monitoring", clsv: "SEED-032", journey: "customer-risk-credit", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-033", product_id: "PRD-005", feature_category_id: "PFCT-007", name: "Booking / Maintenance", clsv: "SEED-033", journey: "servicing", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-034", product_id: "PRD-005", feature_category_id: "PFCT-007", name: "Payments / Billing / Payoff", clsv: "SEED-034", journey: "servicing", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-035", product_id: "PRD-005", feature_category_id: "PFCT-007", name: "Amortization / Accruals", clsv: "SEED-035", journey: "servicing", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-036", product_id: "PRD-005", feature_category_id: "PFCT-007", name: "Transaction Processing", clsv: "SEED-036", journey: "servicing", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-037", product_id: "PRD-005", feature_category_id: "PFCT-002", name: "Covenants / Compliance", clsv: "SEED-037", journey: "monitoring-controls", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-038", product_id: "PRD-005", feature_category_id: "PFCT-002", name: "Exceptions / Amendments", clsv: "SEED-038", journey: "monitoring-controls", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-039", product_id: "PRD-005", feature_category_id: "PFCT-002", name: "Policy Controls", clsv: "SEED-039", journey: "monitoring-controls", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-040", product_id: "PRD-005", feature_category_id: "PFCT-002", name: "Operational Workflow", clsv: "SEED-040", journey: "monitoring-controls", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-041", product_id: "PRD-005", feature_category_id: "PFCT-001", name: "Syndicated Services", clsv: "SEED-041", journey: "syndication", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-042", product_id: "PRD-005", feature_category_id: "PFCT-001", name: "Agented Loan Support", clsv: "SEED-042", journey: "syndication", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-043", product_id: "PRD-005", feature_category_id: "PFCT-001", name: "Multi-Party Administration", clsv: "SEED-043", journey: "syndication", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-044", product_id: "PRD-005", feature_category_id: "PFCT-006", name: "Inquiry / Transaction History", clsv: "SEED-044", journey: "analytics-inquiry", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-045", product_id: "PRD-005", feature_category_id: "PFCT-006", name: "Reporting", clsv: "SEED-045", journey: "analytics-inquiry", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-046", product_id: "PRD-005", feature_category_id: "PFCT-006", name: "BI / Dashboards", clsv: "SEED-046", journey: "analytics-inquiry", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-047", product_id: "PRD-005", feature_category_id: "PFCT-006", name: "Portfolio Visibility", clsv: "SEED-047", journey: "analytics-inquiry", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-048", product_id: "PRD-005", feature_category_id: "PFCT-004", name: "Workflow Engine", clsv: "SEED-048", journey: "platform-services", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-049", product_id: "PRD-005", feature_category_id: "PFCT-004", name: "APIs / Integrations", clsv: "SEED-049", journey: "platform-services", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-050", product_id: "PRD-005", feature_category_id: "PFCT-004", name: "Security / Permissions", clsv: "SEED-050", journey: "platform-services", status: "planned", progress: 0, votes: 0, eta: "TBD" },
  { id: "PF-051", product_id: "PRD-005", feature_category_id: "PFCT-004", name: "Configuration", clsv: "SEED-051", journey: "platform-services", status: "planned", progress: 0, votes: 0, eta: "TBD" },
];

export const ADMIN_SEED_TABLES: SeedTableDefinition[] = [
  { id: "products", label: "products", rows: productsRows },
  { id: "institution_profiles", label: "institution_profiles", rows: institutionProfileRows },
  { id: "product_feature_categories", label: "product_feature_categories", rows: productFeatureCategoryRows },
  { id: "product_features", label: "product_features", rows: productFeaturesRows },
];
